### ISSUE TITLE
Add Coins

### ISSUE THREAD

**Issue by werewolfe** [oipwg/oip-hdmw#5]
The documentation says to add new coins based on names at CoinInfo.name. Is there an example of this? 

I am testing and would like to add DigiByte to my wallet. I've added the network info but `wallet.addCoin('digibyte')` is not working. Any suggestions?

Beautiful work here. I hope I can use it.

**Comment by bitspill** [comment]
You'll need to add a network definition for Digibyte in the networks folder and include in the main exports

add import/export for digibyte https://github.com/oipwg/oip-hdmw/blob/master/src/networks/index.js
 copy/edit to digibyte.js https://github.com/oipwg/oip-hdmw/blob/master/src/networks/litecoin.js

After the network is defined the `wallet.AddCoin` function should work

**Comment by orpheus** [comment]
How did you go about adding the network info?

**Comment by werewolfe** [comment]
Thanks for the help! 

**src/networks/index.js**

`import bitcoin from './bitcoin'
import bitcoin_testnet from './bitcoin_testnet'
import flo from './flo'
import flo_testnet from './flo_testnet'
import litecoin from './litecoin'
import litecoin_testnet from './litecoin_testnet'
import digibyte from './digibyte'

module.exports = {
	bitcoin: bitcoin,
	bitcoin_testnet: bitcoin_testnet,
	flo: flo,
	flo_testnet: flo_testnet,
	litecoin: litecoin,
	litecoin_testnet: litecoin_testnet,
	digibyte: digibyte
}`

**src/networks/config.js**

`module.exports = {
	defaultApiUrls: {
		bitcoin: 'https://bitsight.failover.alexandria.io/api',
		bitcoin_testnet: 'https://bitsight.mk1.alexandria.io/api',
		flo: 'https://livenet.flocha.in/api',
		flo_testnet: 'https://testnet.flocha.in/api',
		litecoin: 'https://litesight.failover.alexandria.io/api',
		litecoin_testnet: 'https://litesight.mk1.alexandria.io/api',
		digibyte: 'https://digiexplorer.info/api'
	},`

**src/networks/digibyte.js**

`import { Insight } from 'insight-explorer'
import coininfo from 'coininfo'
import bip44constants from 'bip44-constants'
import config from "./config";

var digibyteFeePerKb = 100000

var n = coininfo.digibyte.main.toBitcoinJS();

module.exports = {
	name: 'digibyte',
	displayName: 'DigiByte',
	ticker: 'DGB',
	satPerCoin: 1e8,
	feePerKb: digibyteFeePerKb,
	feePerByte: digibyteFeePerKb / 1024,
	maxFeePerByte: 100,
	minFee: digibyteFeePerKb,
	dust: 54600,

	txVersion: 1,

	explorer: new Insight(config.defaultApiUrls.digibyte),

	getExtraBytes: function(options){ return },

	network: {
		bip32: {
			public: n.bip32.public,
			private: n.bip32.private
		},
		slip44: bip44constants.DGB,
		messagePrefix: '\x18DigiByte Signed Message:\n',
		pubKeyHash: n.pubKeyHash,
		scriptHash: n.scriptHash,
		wif: n.wif
	}
}`

digibyte is undefined here:

`this.myWallet.addCoin("digibyte");
    this.show = this.myWallet.getCoins();
    
    console.log(this.show);
    let bitcoin = this.myWallet.getCoin('bitcoin');
    let litecoin = this.myWallet.getCoin('litecoin');
    --> let digibyte = this.myWallet.getCoin('digibyte'); //Undefined

    let myMainAddress = bitcoin.getMainAddress();
    let myMainAddress2 = litecoin.getMainAddress();
    let myMainAddress3 = digibyte.getMainAddress();`

**Comment by bitspill** [comment]
DigiByte at [cryptocoinjs/coininfo ](https://github.com/cryptocoinjs/coininfo)doesn't define the main.versions.bip32.public/private values so the `n.bitp32.public/private` values can't be used in the `networks/digibyte.js` file

https://github.com/cryptocoinjs/coininfo/blob/master/lib/coins/dgb.js


You can either submit an upstream PR to get those values added to cryptocoinjs/coininfo or specify them directly similar to Flo https://github.com/oipwg/oip-hdmw/blob/master/src/networks/flo.js#L104-L105

**Comment by bitspill** [comment]
Relevant values from DGB Core are https://github.com/digibyte/digibyte/blob/master/src/chainparams.cpp#L228-L229

Which would mean setting
```bip32: {
  public: 0x0488B21E,
  private: 0x0488ADE4
},```

**Comment by werewolfe** [comment]
I appreciate the forensic work. I added the values, but still get the undefined error.
Here's what I added for DigiByte:
```
network: {
		bip32: {
			public: 0x0488B21E,
                         private: 0x0488ADE4
		},
		slip44: bip44constants.DGB,
		messagePrefix: '\x18DigiByte Signed Message:\n',
		pubKeyHash: n.pubKeyHash,
		scriptHash: n.scriptHash,
		wif: n.wif
	}
```
```
{bitcoin: Coin, litecoin: Coin, flo: Coin}
bitcoin: Coin {seed: "xprv9vcfHyWDcCZ6jEbYNrhcn2Axn6RJrqP3xjswkTbNrCPxNe…jiMDBg7Tfsfn3ipZAuhArfgrCrsbKyu4PKS6PGbtsZUGf2wxh", coin: {…}, discover: true, root: BIP32, accounts: {…}, …}
flo: Coin {seed: "xprv9vcfHyWDcCZ6jEbYNrhcn2Axn6RJrqP3xjswkTbNrCPxNe…jiMDBg7Tfsfn3ipZAuhArfgrCrsbKyu4PKS6PGbtsZUGf2wxh", coin: {…}, discover: true, root: BIP32, accounts: {…}, …}
litecoin: Coin {seed: "xprv9vcfHyWDcCZ6jEbYNrhcn2Axn6RJrqP3xjswkTbNrCPxNe…jiMDBg7Tfsfn3ipZAuhArfgrCrsbKyu4PKS6PGbtsZUGf2wxh", coin: {…}, discover: true, root: BIP32, accounts: {…}, …}
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'getMainAddress' of undefined
```
