### ISSUE TITLE
can't check balance, view recent transactions, or send FLO on wallet.oip.io

### ISSUE THREAD

**Issue by metacoin** [oipwg/oip-hdmw#8]
I generated about 90 mnemonics, logged in, and then refreshed the page and eventually the FLO wallet stopped working. The Bitcoin wallet is already in this state, and now the FLO wallet is too.

Seems like for other people it's still working, but even in different browsers and with cookies cleared, I am getting this error
![Screenshot from 2019-06-09 21-57-46](https://user-images.githubusercontent.com/4959276/59167960-af130c00-8b01-11e9-8135-75f0ace01151.png)

edit: @bitspill mentioned that the Litecoin explorer was rate limiting people aggressively. It's possible this is an explorer rate limit issue

**Comment by orpheus** [comment]
could you post a snapshot of the network tab on first load?

**Comment by metacoin** [comment]
It looks like the FLO wallet started working again, but the Bitcoin wallet still errors out. Here's a screenshot of the network tab 
![Screenshot from 2019-06-11 11-00-22](https://user-images.githubusercontent.com/4959276/59283231-3cf11300-8c38-11e9-8def-15700b86c36a.png)

**Comment by orpheus** [comment]
`https://bitsight.failover.alexandria.io` hasn't been running for a while. I'd contact devon or ksa if we want to get that back up. For now, you can do two things:

1) Go to settings and change the bitcoin api explorer url to an insight explorer you know to be alive.
2) Go to settings, hide bitcoin, and save so it won't show later.

These are explorer/network issues and not `oip-hdmw`. You can add a ticket to `oip-hdmw-interface` for better error handling, but that's something that was going to go into version 2 of the web app which I have not had time to get to.
